# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_key_response import CreateKeyResponse
from ..types.list_keys_response import ListKeysResponse
from ..types.rotate_key_response import RotateKeyResponse
from .raw_client import AsyncRawApiKeysClient, RawApiKeysClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ApiKeysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiKeysClient
        """
        return self._raw_client

    def list_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListKeysResponse:
        """
        Lists all named API keys for the tenant. Keys are masked (only prefix shown).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKeysResponse
            List of API keys

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.list_keys()
        """
        _response = self._raw_client.list_keys(request_options=request_options)
        return _response.data

    def create_key(self, *, name: str, request_options: typing.Optional[RequestOptions] = None) -> CreateKeyResponse:
        """
        Creates a new named API key for the tenant. The raw key value is returned
        once in the response and never stored — only its SHA-256 hash is persisted.

        Limits tenants to MAX_KEYS_PER_TENANT keys.

        Parameters
        ----------
        name : str
            Human-readable name for the key (e.g., "Production", "Staging").

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateKeyResponse
            API key created (shown once)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.create_key(
            name="name",
        )
        """
        _response = self._raw_client.create_key(name=name, request_options=request_options)
        return _response.data

    def rotate_key(self, *, request_options: typing.Optional[RequestOptions] = None) -> RotateKeyResponse:
        """
        Generates a new API key, updates the tenant record in the store, replaces
        the API key reference, updates cache mappings, and invalidates the old key.
        After rotation, the old key will be rejected with 401 on subsequent requests.

        - If the tenant record cannot be found: returns 500 (should not happen since
          auth middleware already resolved the tenant).
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the new API key (shown only once).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateKeyResponse
            Key rotated (new key shown once)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.rotate_key()
        """
        _response = self._raw_client.rotate_key(request_options=request_options)
        return _response.data

    def delete_key(self, key_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revokes (deletes) a specific API key by its key_id. Removes both the
        tenant-scoped record and the global API key reference, and invalidates
        the key in cache.

        Parameters
        ----------
        key_id : str
            The key identifier to revoke

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.api_keys.delete_key(
            key_id="key_id",
        )
        """
        _response = self._raw_client.delete_key(key_id, request_options=request_options)
        return _response.data


class AsyncApiKeysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiKeysClient
        """
        return self._raw_client

    async def list_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListKeysResponse:
        """
        Lists all named API keys for the tenant. Keys are masked (only prefix shown).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKeysResponse
            List of API keys

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.list_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_keys(request_options=request_options)
        return _response.data

    async def create_key(
        self, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateKeyResponse:
        """
        Creates a new named API key for the tenant. The raw key value is returned
        once in the response and never stored — only its SHA-256 hash is persisted.

        Limits tenants to MAX_KEYS_PER_TENANT keys.

        Parameters
        ----------
        name : str
            Human-readable name for the key (e.g., "Production", "Staging").

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateKeyResponse
            API key created (shown once)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.create_key(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_key(name=name, request_options=request_options)
        return _response.data

    async def rotate_key(self, *, request_options: typing.Optional[RequestOptions] = None) -> RotateKeyResponse:
        """
        Generates a new API key, updates the tenant record in the store, replaces
        the API key reference, updates cache mappings, and invalidates the old key.
        After rotation, the old key will be rejected with 401 on subsequent requests.

        - If the tenant record cannot be found: returns 500 (should not happen since
          auth middleware already resolved the tenant).
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the new API key (shown only once).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateKeyResponse
            Key rotated (new key shown once)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.rotate_key()


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_key(request_options=request_options)
        return _response.data

    async def delete_key(self, key_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revokes (deletes) a specific API key by its key_id. Removes both the
        tenant-scoped record and the global API key reference, and invalidates
        the key in cache.

        Parameters
        ----------
        key_id : str
            The key identifier to revoke

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.api_keys.delete_key(
                key_id="key_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_key(key_id, request_options=request_options)
        return _response.data
