# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_portal_token_response import CreatePortalTokenResponse
from .raw_client import AsyncRawBillingClient, RawBillingClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def create_portal_token(
        self, *, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalTokenResponse:
        """
        Generates a signed JWT that grants a specific subject access to the hosted
        billing portal. The token is scoped to both the tenant and the subject,
        preventing cross-tenant or cross-subject access.

        ## Authentication
        Requires API key authentication (X-Api-Key header). Only the tenant's
        backend should call this endpoint.

        ## Request Body
        ```json
        { "subject_id": "user_123" }
        ```

        ## Response (200)
        ```json
        {
          "token": "eyJ...",
          "portal_url": "https://billing.billkit.io/acme-corp/manage?token=eyJ...",
          "expires_at": "2024-01-15T12:30:00Z"
        }
        ```

        ## Errors
        - 400: Missing or empty `subject_id`
        - 404: Subject not found or not assigned to this tenant
        - 500: Internal error (JWT signing failure, store error)

        Parameters
        ----------
        subject_id : str
            The subject (end user) to generate a portal token for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalTokenResponse
            Portal token generated

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.billing.create_portal_token(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.create_portal_token(subject_id=subject_id, request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def create_portal_token(
        self, *, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreatePortalTokenResponse:
        """
        Generates a signed JWT that grants a specific subject access to the hosted
        billing portal. The token is scoped to both the tenant and the subject,
        preventing cross-tenant or cross-subject access.

        ## Authentication
        Requires API key authentication (X-Api-Key header). Only the tenant's
        backend should call this endpoint.

        ## Request Body
        ```json
        { "subject_id": "user_123" }
        ```

        ## Response (200)
        ```json
        {
          "token": "eyJ...",
          "portal_url": "https://billing.billkit.io/acme-corp/manage?token=eyJ...",
          "expires_at": "2024-01-15T12:30:00Z"
        }
        ```

        ## Errors
        - 400: Missing or empty `subject_id`
        - 404: Subject not found or not assigned to this tenant
        - 500: Internal error (JWT signing failure, store error)

        Parameters
        ----------
        subject_id : str
            The subject (end user) to generate a portal token for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePortalTokenResponse
            Portal token generated

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.billing.create_portal_token(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_portal_token(subject_id=subject_id, request_options=request_options)
        return _response.data
