# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_assignment_response import CreateAssignmentResponse
from .raw_client import AsyncRawAssignmentsClient, RawAssignmentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AssignmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAssignmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAssignmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAssignmentsClient
        """
        return self._raw_client

    def create_assignment(
        self, *, plan_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAssignmentResponse:
        """
        Assigns a plan to a subject. Validates that the plan key exists in the tenant's
        schema, writes the assignment to the store, and invalidates the subject's cache entries.

        - If the request body is missing or malformed: returns 400.
        - If the subject_id exceeds 256 characters: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the plan key does not exist in the schema: returns 422.
        - If a store or cache error occurs: returns 500.
        - On success: returns 201 with the assignment details.

        Parameters
        ----------
        plan_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAssignmentResponse
            Assignment created

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.assignments.create_assignment(
            plan_key="plan_key",
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.create_assignment(
            plan_key=plan_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data

    def delete_assignment(self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Removes the subject assignment from the store and invalidates the subject's
        cache entries. Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If subject_id is empty: returns 400.
        - If a store error occurs: returns 500.
        - On success: returns 204 No Content (regardless of whether the assignment existed).
          The `max_subjects` self-metering counter is only decremented when an
          assignment actually existed, so repeated or no-op deletes cannot drive
          the counter negative.

        Parameters
        ----------
        subject_id : str
            The subject identifier to unassign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.assignments.delete_assignment(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.delete_assignment(subject_id, request_options=request_options)
        return _response.data


class AsyncAssignmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAssignmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAssignmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAssignmentsClient
        """
        return self._raw_client

    async def create_assignment(
        self, *, plan_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAssignmentResponse:
        """
        Assigns a plan to a subject. Validates that the plan key exists in the tenant's
        schema, writes the assignment to the store, and invalidates the subject's cache entries.

        - If the request body is missing or malformed: returns 400.
        - If the subject_id exceeds 256 characters: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the plan key does not exist in the schema: returns 422.
        - If a store or cache error occurs: returns 500.
        - On success: returns 201 with the assignment details.

        Parameters
        ----------
        plan_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAssignmentResponse
            Assignment created

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.assignments.create_assignment(
                plan_key="plan_key",
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_assignment(
            plan_key=plan_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data

    async def delete_assignment(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Removes the subject assignment from the store and invalidates the subject's
        cache entries. Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If subject_id is empty: returns 400.
        - If a store error occurs: returns 500.
        - On success: returns 204 No Content (regardless of whether the assignment existed).
          The `max_subjects` self-metering counter is only decremented when an
          assignment actually existed, so repeated or no-op deletes cannot drive
          the counter negative.

        Parameters
        ----------
        subject_id : str
            The subject identifier to unassign

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.assignments.delete_assignment(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_assignment(subject_id, request_options=request_options)
        return _response.data
