# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.pricing_response import PricingResponse
from .raw_client import AsyncRawPricingClient, RawPricingClient


class PricingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPricingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPricingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPricingClient
        """
        return self._raw_client

    def get_pricing(self, *, request_options: typing.Optional[RequestOptions] = None) -> PricingResponse:
        """
        Returns the authenticated tenant's pricing information formatted for a
        pricing page. Plans are sorted by price ascending, features are ordered
        by type (boolean → metered → stateful → attribute), and all values are
        formatted for direct display.

        Supports conditional requests via `ETag` / `If-None-Match` headers.
        Returns 304 Not Modified when the schema has not changed.

        Responses are cached in Valkey with a 15-minute sliding TTL. Cache is
        checked before DynamoDB to minimize latency for hot pricing pages.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PricingResponse
            Pricing response

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.pricing.get_pricing()
        """
        _response = self._raw_client.get_pricing(request_options=request_options)
        return _response.data


class AsyncPricingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPricingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPricingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPricingClient
        """
        return self._raw_client

    async def get_pricing(self, *, request_options: typing.Optional[RequestOptions] = None) -> PricingResponse:
        """
        Returns the authenticated tenant's pricing information formatted for a
        pricing page. Plans are sorted by price ascending, features are ordered
        by type (boolean → metered → stateful → attribute), and all values are
        formatted for direct display.

        Supports conditional requests via `ETag` / `If-None-Match` headers.
        Returns 304 Not Modified when the schema has not changed.

        Responses are cached in Valkey with a 15-minute sliding TTL. Cache is
        checked before DynamoDB to minimize latency for hot pricing pages.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PricingResponse
            Pricing response

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.pricing.get_pricing()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_pricing(request_options=request_options)
        return _response.data
