# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.set_usage_response import SetUsageResponse
from ..types.usage_response import UsageResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawUsageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def set_usage(
        self, subject_id: str, feature_code: str, *, value: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SetUsageResponse]:
        """
        Sets the absolute value of a stateful feature counter. Enforces limits at write time:
        if the requested value exceeds the configured max, the request is rejected with 409.
        Writes directly to cache (bypassing the increment buffer) and publishes a `UsageSetEvent`
        to SQS for durable persistence.

        - If `subject_id` or `feature_code` is empty: returns 400.
        - If `feature_code` not found in schema: returns 404.
        - If feature type is not Stateful: returns 422.
        - If subject has no plan assigned: returns 409 with reason "no_plan".
        - If value exceeds max: returns 409 with reason "value exceeds stateful feature limit".
        - If cache write fails: returns 503.
        - On SQS publish failure: still returns 200 (fire-and-forget).
        - On success: returns 200 with accepted response.

        Parameters
        ----------
        subject_id : str
            The subject whose counter is being set

        feature_code : str
            The stateful feature code (e.g., "seats")

        value : int
            The absolute counter value to set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SetUsageResponse]
            Counter set successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"subjects/{encode_path_param(subject_id)}/usage/{encode_path_param(feature_code)}",
            method="PUT",
            json={
                "value": value,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SetUsageResponse,
                    parse_obj_as(
                        type_=SetUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_usage(
        self, *, per_subject: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[UsageResponse]:
        """
        Returns aggregated usage statistics for the authenticated tenant.
        Includes per-feature consumption totals and cadence window metadata.

        Plan-specific fields (limit, cadence, overage, warning) are intentionally
        omitted from the aggregated view because they are per-plan values that
        cannot be meaningfully resolved at the tenant level (see issue #224).

        When `?per_subject=true` is passed, returns per-subject usage breakdowns
        including each subject's feature counters with plan-specific limits
        resolved from the schema.

        Parameters
        ----------
        per_subject : typing.Optional[bool]
            When true, returns per-subject usage breakdowns

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UsageResponse]
            Usage statistics
        """
        _response = self._client_wrapper.httpx_client.request(
            "usage",
            method="GET",
            params={
                "per_subject": per_subject,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageResponse,
                    parse_obj_as(
                        type_=UsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawUsageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def set_usage(
        self, subject_id: str, feature_code: str, *, value: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SetUsageResponse]:
        """
        Sets the absolute value of a stateful feature counter. Enforces limits at write time:
        if the requested value exceeds the configured max, the request is rejected with 409.
        Writes directly to cache (bypassing the increment buffer) and publishes a `UsageSetEvent`
        to SQS for durable persistence.

        - If `subject_id` or `feature_code` is empty: returns 400.
        - If `feature_code` not found in schema: returns 404.
        - If feature type is not Stateful: returns 422.
        - If subject has no plan assigned: returns 409 with reason "no_plan".
        - If value exceeds max: returns 409 with reason "value exceeds stateful feature limit".
        - If cache write fails: returns 503.
        - On SQS publish failure: still returns 200 (fire-and-forget).
        - On success: returns 200 with accepted response.

        Parameters
        ----------
        subject_id : str
            The subject whose counter is being set

        feature_code : str
            The stateful feature code (e.g., "seats")

        value : int
            The absolute counter value to set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SetUsageResponse]
            Counter set successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"subjects/{encode_path_param(subject_id)}/usage/{encode_path_param(feature_code)}",
            method="PUT",
            json={
                "value": value,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SetUsageResponse,
                    parse_obj_as(
                        type_=SetUsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_usage(
        self, *, per_subject: typing.Optional[bool] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[UsageResponse]:
        """
        Returns aggregated usage statistics for the authenticated tenant.
        Includes per-feature consumption totals and cadence window metadata.

        Plan-specific fields (limit, cadence, overage, warning) are intentionally
        omitted from the aggregated view because they are per-plan values that
        cannot be meaningfully resolved at the tenant level (see issue #224).

        When `?per_subject=true` is passed, returns per-subject usage breakdowns
        including each subject's feature counters with plan-specific limits
        resolved from the schema.

        Parameters
        ----------
        per_subject : typing.Optional[bool]
            When true, returns per-subject usage breakdowns

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UsageResponse]
            Usage statistics
        """
        _response = await self._client_wrapper.httpx_client.request(
            "usage",
            method="GET",
            params={
                "per_subject": per_subject,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageResponse,
                    parse_obj_as(
                        type_=UsageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
