# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.attach_addon_response import AttachAddonResponse
from .raw_client import AsyncRawAddonsClient, RawAddonsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AddonsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAddonsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAddonsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAddonsClient
        """
        return self._raw_client

    def attach_addon(
        self, *, addon_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AttachAddonResponse:
        """
        Validates that the add-on key exists in the tenant's schema, attaches it to
        the subject's existing assignment in the store, and invalidates the subject's
        cache entries.

        - If the request body is missing or malformed: returns 400 (via Axum rejection).
        - If subject_id or addon_key is empty: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the add-on key does not exist in the schema: returns 422.
        - If the subject has no existing assignment: returns 404.
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the updated add-on list.

        Parameters
        ----------
        addon_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachAddonResponse
            Add-on attached

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.addons.attach_addon(
            addon_key="addon_key",
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.attach_addon(
            addon_key=addon_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data

    def detach_addon(
        self, subject_id: str, addon_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Removes the given add-on from the subject's existing assignment in the store
        and invalidates the subject's cache entries. Tenant is resolved from
        `X-Api-Key` via the auth middleware.

        - If subject_id or addon_key is empty: returns 400.
        - If the subject has no existing assignment: returns 404.
        - If a store error occurs: returns 500.
        - On success: returns 204 No Content, whether or not the add-on was
          actually attached (idempotent, matching `DELETE /assignments/{subject_id}`).

        Parameters
        ----------
        subject_id : str
            The subject identifier

        addon_key : str
            The add-on key to detach

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.addons.detach_addon(
            subject_id="subject_id",
            addon_key="addon_key",
        )
        """
        _response = self._raw_client.detach_addon(subject_id, addon_key, request_options=request_options)
        return _response.data


class AsyncAddonsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAddonsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAddonsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAddonsClient
        """
        return self._raw_client

    async def attach_addon(
        self, *, addon_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AttachAddonResponse:
        """
        Validates that the add-on key exists in the tenant's schema, attaches it to
        the subject's existing assignment in the store, and invalidates the subject's
        cache entries.

        - If the request body is missing or malformed: returns 400 (via Axum rejection).
        - If subject_id or addon_key is empty: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the add-on key does not exist in the schema: returns 422.
        - If the subject has no existing assignment: returns 404.
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the updated add-on list.

        Parameters
        ----------
        addon_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachAddonResponse
            Add-on attached

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.addons.attach_addon(
                addon_key="addon_key",
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.attach_addon(
            addon_key=addon_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data

    async def detach_addon(
        self, subject_id: str, addon_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Removes the given add-on from the subject's existing assignment in the store
        and invalidates the subject's cache entries. Tenant is resolved from
        `X-Api-Key` via the auth middleware.

        - If subject_id or addon_key is empty: returns 400.
        - If the subject has no existing assignment: returns 404.
        - If a store error occurs: returns 500.
        - On success: returns 204 No Content, whether or not the add-on was
          actually attached (idempotent, matching `DELETE /assignments/{subject_id}`).

        Parameters
        ----------
        subject_id : str
            The subject identifier

        addon_key : str
            The add-on key to detach

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.addons.detach_addon(
                subject_id="subject_id",
                addon_key="addon_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.detach_addon(subject_id, addon_key, request_options=request_options)
        return _response.data
