# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .addon_definition import AddonDefinition
    from .addon_type import AddonType
    from .apply_contract_response import ApplyContractResponse
    from .attach_addon_response import AttachAddonResponse
    from .attribute_data_type import AttributeDataType
    from .batch_register_response import BatchRegisterResponse
    from .batch_subject_result import BatchSubjectResult
    from .billing_config import BillingConfig
    from .billing_cycle import BillingCycle
    from .cadence import Cadence
    from .contract_definition import ContractDefinition
    from .create_assignment_response import CreateAssignmentResponse
    from .create_key_response import CreateKeyResponse
    from .create_portal_token_response import CreatePortalTokenResponse
    from .decision import Decision
    from .feature_definition import FeatureDefinition
    from .feature_type import FeatureType
    from .feature_value import FeatureValue
    from .gate_response import GateResponse
    from .invoice_line_item_response import InvoiceLineItemResponse
    from .invoice_list_item import InvoiceListItem
    from .invoice_preview_response import InvoicePreviewResponse
    from .key_list_item import KeyListItem
    from .limit import Limit
    from .limit_definition import LimitDefinition
    from .limit_one import LimitOne
    from .list_invoices_params import ListInvoicesParams
    from .list_invoices_response import ListInvoicesResponse
    from .list_keys_response import ListKeysResponse
    from .overage_info import OverageInfo
    from .overage_policy import OveragePolicy
    from .plan_definition import PlanDefinition
    from .preview_overage_item import PreviewOverageItem
    from .pricing_billing import PricingBilling
    from .pricing_feature import PricingFeature
    from .pricing_metadata import PricingMetadata
    from .pricing_plan import PricingPlan
    from .pricing_response import PricingResponse
    from .rate_card_dimension import RateCardDimension
    from .rate_card_response import RateCardResponse
    from .register_subject_request import RegisterSubjectRequest
    from .register_subject_response import RegisterSubjectResponse
    from .rotate_key_response import RotateKeyResponse
    from .schema_document import SchemaDocument
    from .subject_detail_response import SubjectDetailResponse
    from .subject_info import SubjectInfo
    from .subjects_response import SubjectsResponse
    from .tenant_me_response import TenantMeResponse
    from .validation_error import ValidationError
    from .validation_error_response import ValidationErrorResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AddonDefinition": ".addon_definition",
    "AddonType": ".addon_type",
    "ApplyContractResponse": ".apply_contract_response",
    "AttachAddonResponse": ".attach_addon_response",
    "AttributeDataType": ".attribute_data_type",
    "BatchRegisterResponse": ".batch_register_response",
    "BatchSubjectResult": ".batch_subject_result",
    "BillingConfig": ".billing_config",
    "BillingCycle": ".billing_cycle",
    "Cadence": ".cadence",
    "ContractDefinition": ".contract_definition",
    "CreateAssignmentResponse": ".create_assignment_response",
    "CreateKeyResponse": ".create_key_response",
    "CreatePortalTokenResponse": ".create_portal_token_response",
    "Decision": ".decision",
    "FeatureDefinition": ".feature_definition",
    "FeatureType": ".feature_type",
    "FeatureValue": ".feature_value",
    "GateResponse": ".gate_response",
    "InvoiceLineItemResponse": ".invoice_line_item_response",
    "InvoiceListItem": ".invoice_list_item",
    "InvoicePreviewResponse": ".invoice_preview_response",
    "KeyListItem": ".key_list_item",
    "Limit": ".limit",
    "LimitDefinition": ".limit_definition",
    "LimitOne": ".limit_one",
    "ListInvoicesParams": ".list_invoices_params",
    "ListInvoicesResponse": ".list_invoices_response",
    "ListKeysResponse": ".list_keys_response",
    "OverageInfo": ".overage_info",
    "OveragePolicy": ".overage_policy",
    "PlanDefinition": ".plan_definition",
    "PreviewOverageItem": ".preview_overage_item",
    "PricingBilling": ".pricing_billing",
    "PricingFeature": ".pricing_feature",
    "PricingMetadata": ".pricing_metadata",
    "PricingPlan": ".pricing_plan",
    "PricingResponse": ".pricing_response",
    "RateCardDimension": ".rate_card_dimension",
    "RateCardResponse": ".rate_card_response",
    "RegisterSubjectRequest": ".register_subject_request",
    "RegisterSubjectResponse": ".register_subject_response",
    "RotateKeyResponse": ".rotate_key_response",
    "SchemaDocument": ".schema_document",
    "SubjectDetailResponse": ".subject_detail_response",
    "SubjectInfo": ".subject_info",
    "SubjectsResponse": ".subjects_response",
    "TenantMeResponse": ".tenant_me_response",
    "ValidationError": ".validation_error",
    "ValidationErrorResponse": ".validation_error_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddonDefinition",
    "AddonType",
    "ApplyContractResponse",
    "AttachAddonResponse",
    "AttributeDataType",
    "BatchRegisterResponse",
    "BatchSubjectResult",
    "BillingConfig",
    "BillingCycle",
    "Cadence",
    "ContractDefinition",
    "CreateAssignmentResponse",
    "CreateKeyResponse",
    "CreatePortalTokenResponse",
    "Decision",
    "FeatureDefinition",
    "FeatureType",
    "FeatureValue",
    "GateResponse",
    "InvoiceLineItemResponse",
    "InvoiceListItem",
    "InvoicePreviewResponse",
    "KeyListItem",
    "Limit",
    "LimitDefinition",
    "LimitOne",
    "ListInvoicesParams",
    "ListInvoicesResponse",
    "ListKeysResponse",
    "OverageInfo",
    "OveragePolicy",
    "PlanDefinition",
    "PreviewOverageItem",
    "PricingBilling",
    "PricingFeature",
    "PricingMetadata",
    "PricingPlan",
    "PricingResponse",
    "RateCardDimension",
    "RateCardResponse",
    "RegisterSubjectRequest",
    "RegisterSubjectResponse",
    "RotateKeyResponse",
    "SchemaDocument",
    "SubjectDetailResponse",
    "SubjectInfo",
    "SubjectsResponse",
    "TenantMeResponse",
    "ValidationError",
    "ValidationErrorResponse",
]
