# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_cycle import BillingCycle


class BillingConfig(UniversalBaseModel):
    """
    Billing configuration for a schema, enabling invoicing features.
    """

    billing_cycle: BillingCycle = pydantic.Field()
    """
    How often invoices are generated
    """

    currency: str = pydantic.Field()
    """
    ISO 4217 currency code (e.g., "USD", "EUR", "GBP")
    """

    delinquency_grace_days: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of grace days before delinquency enforcement kicks in
    """

    deny_on_delinquency: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to deny access when a subject is delinquent
    """

    require_autopay: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether subjects must have a payment method on file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
