# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChangePlanResponse(UniversalBaseModel):
    """
    Response body for a successful plan change.
    """

    changed_at: str = pydantic.Field()
    """
    ISO 8601 timestamp of when the change was recorded.
    """

    effective: str = pydantic.Field()
    """
    "immediate" for upgrades and lateral/no-billing changes, "next_cycle" for downgrades.
    """

    new_plan_key: str = pydantic.Field()
    """
    The plan the subject is now on (or will be on at next cycle).
    """

    previous_plan_key: str = pydantic.Field()
    """
    The plan the subject was on before the change.
    """

    proration_charge_cents: int = pydantic.Field()
    """
    Amount immediately charged for upgrade proration, in cents. 0 if none was charged.
    """

    subject_id: str = pydantic.Field()
    """
    The subject whose plan was changed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
