# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckoutFallbackResponse(UniversalBaseModel):
    """
    Response body for `POST /subjects/checkout-fallback`.
    """

    base_invoice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The window-1 `Base` invoice id written for prepaid (absent for postpaid).
    """

    billing_mode: str
    billing_status: str
    subject_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
