# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreatePortalTokenResponse(UniversalBaseModel):
    """
    Successful response for `POST /billing/portal-token`.
    """

    expires_at: str = pydantic.Field()
    """
    Token expiration time (ISO 8601).
    """

    portal_url: str = pydantic.Field()
    """
    The full portal URL the end user should be redirected to.
    """

    token: str = pydantic.Field()
    """
    The signed JWT token.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
