# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FeatureUsage(UniversalBaseModel):
    """
    A single feature's usage statistics in the response.
    """

    billing_period_usage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Cumulative usage across all cadence windows in the current billing period.
    Only present when the tenant has a billing configuration.
    """

    cadence: typing.Optional[str] = pydantic.Field(default=None)
    """
    The cadence window (e.g., "monthly", "daily") if applicable.
    """

    feature_code: str = pydantic.Field()
    """
    The feature code (key in the schema features map).
    """

    feature_type: str = pydantic.Field()
    """
    The feature type (metered, stateful, boolean, attribute).
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    The plan limit for this feature (null if unlimited or not applicable).
    """

    overage: typing.Optional[str] = pydantic.Field(default=None)
    """
    The overage policy ("block" or "soft") if applicable.
    """

    resets_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the counter will next reset (ISO 8601, equal to window_end). Only present for metered features with a cadence.
    """

    total_usage: int = pydantic.Field()
    """
    Total consumption across all subjects for this feature in the current cadence window.
    """

    warning: bool = pydantic.Field()
    """
    Whether usage exceeds 80% of the limit (warning threshold).
    """

    window_end: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    End of the current cadence window (ISO 8601). Only present for metered features with a cadence.
    """

    window_start: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Start of the current cadence window (ISO 8601). Only present for metered features with a cadence.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
