# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .attribute_data_type import AttributeDataType
from .feature_type import FeatureType


class FeatureDefinition(UniversalBaseModel):
    """
    Definition of a single feature in the entitlement schema.
    """

    data_type: typing.Optional[AttributeDataType] = None
    type: FeatureType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
