# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FeatureUsage(UniversalBaseModel):
    """
    A single feature's usage statistics in the aggregated response.

    Plan-specific fields (limit, cadence, overage, warning) are intentionally
    omitted from the aggregated view because they are per-plan and cannot be
    meaningfully resolved at the tenant level. Use `?per_subject=true` for
    per-subject usage with plan-specific limits.
    """

    billing_period_usage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Cumulative usage across all cadence windows in the current billing period.
    Only present when the tenant has a billing configuration.
    """

    feature_code: str = pydantic.Field()
    """
    The feature code (key in the schema features map).
    """

    feature_type: str = pydantic.Field()
    """
    The feature type (metered, stateful, boolean, attribute).
    """

    resets_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the counter will next reset (ISO 8601, equal to window_end). Only present for metered features with a cadence.
    """

    total_usage: int = pydantic.Field()
    """
    Total consumption across all subjects for this feature in the current cadence window.
    """

    window_end: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    End of the current cadence window (ISO 8601). Only present for metered features with a cadence.
    """

    window_start: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Start of the current cadence window (ISO 8601). Only present for metered features with a cadence.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
