# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .decision import Decision


class GateResponse(UniversalBaseModel):
    """
    Response returned by the `POST /check` endpoint.
    """

    attribute_value: typing.Optional[typing.Any] = None
    decision: Decision
    overage: typing.Optional[bool] = None
    reason: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
