# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .invoice_line_item_response import InvoiceLineItemResponse


class InvoiceListItem(UniversalBaseModel):
    """
    A single invoice in the list response.
    """

    amount_cents: int
    billing_period_end: str
    billing_period_start: str
    created_at: str
    currency: str
    invoice_id: str
    line_items: typing.List[InvoiceLineItemResponse]
    paid_at: typing.Optional[str] = None
    status: str
    stripe_invoice_id: str
    subject_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
