# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .invoice_line_item_response import InvoiceLineItemResponse
from .preview_overage_item import PreviewOverageItem


class InvoicePreviewResponse(UniversalBaseModel):
    """
    Response body for `GET /invoices/:subject_id/preview`.
    """

    base_price_cents: int
    currency: str
    line_items: typing.List[InvoiceLineItemResponse]
    overage_items: typing.List[PreviewOverageItem]
    plan_key: str
    subject_id: str
    total_cents: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
