# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InvoiceFailureItem(UniversalBaseModel):
    """
    A single invoice-failure marker in the list response.
    """

    attempt_count: int
    error: str
    exhausted: bool
    first_failed_at: str
    last_failed_at: str
    subject_id: str
    window_end: str
    window_start: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
