# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListInvoiceFailuresParams(UniversalBaseModel):
    """
    Query parameters for `GET /invoice-failures`.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pagination: opaque cursor from a previous response's `next_cursor` field.
    """

    exhausted: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Filter by whether the retry budget is exhausted. When omitted, both
    retryable and exhausted markers are returned.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Pagination: maximum number of items to return per page (1–1000, default 100).
    """

    subject_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by subject ID.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
