# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListInvoicesParams(UniversalBaseModel):
    """
    Query parameters for `GET /invoices`.
    """

    end_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter: only include invoices with billing_period_start <= end_date.
    """

    start_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter: only include invoices with billing_period_end >= start_date.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by invoice status (e.g., "open", "paid", "past_due", "uncollectible").
    """

    subject_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by subject ID.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
