# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .platform_invoice_item import PlatformInvoiceItem


class ListPlatformInvoicesResponse(UniversalBaseModel):
    """
    Response body for `GET /invoices/platform`.
    """

    invoices: typing.List[PlatformInvoiceItem] = pydantic.Field()
    """
    List of platform invoices, sorted by created_at descending.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
