# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .invoice_failure_item import InvoiceFailureItem


class ListInvoiceFailuresResponse(UniversalBaseModel):
    """
    Response body for `GET /invoice-failures`.
    """

    failures: typing.List[InvoiceFailureItem]
    has_more: bool = pydantic.Field()
    """
    Whether more results exist beyond this page.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor for the next page. Null/absent on the last page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
