# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MonthlyRevenue(UniversalBaseModel):
    """
    Monthly revenue breakdown entry.
    """

    collected_cents: int = pydantic.Field()
    """
    Sum of `amount_cents` for invoices with status "paid" in this month.
    """

    invoice_count: int = pydantic.Field()
    """
    Total number of invoices in this month (regardless of status).
    """

    month: str = pydantic.Field()
    """
    Month in YYYY-MM format (derived from `billing_period_end`).
    """

    outstanding_cents: int = pydantic.Field()
    """
    Sum of `amount_cents` for invoices with status "open" or "past_due" in this month.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
