# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaginationQuery(UniversalBaseModel):
    """
    Query parameters for paginated list endpoints.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque pagination cursor from a previous response's `next_cursor` field.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of items to return per page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
