# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .limit_definition import LimitDefinition


class PlanDefinition(UniversalBaseModel):
    """
    Plan definition within a schema.
    """

    attributes: typing.Optional[typing.Dict[str, typing.Any]] = None
    display_name: typing.Optional[str] = None
    grants: typing.Optional[typing.Dict[str, typing.Optional[bool]]] = None
    inherits: typing.Optional[str] = None
    limits: typing.Optional[typing.Dict[str, typing.Optional[LimitDefinition]]] = None
    price: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
