# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PlatformInvoiceItem(UniversalBaseModel):
    """
    A single platform invoice item in the response.
    """

    amount_cents: int = pydantic.Field()
    """
    Total amount in cents.
    """

    created_at: str = pydantic.Field()
    """
    RFC 3339 timestamp of when the invoice was created.
    """

    id: str = pydantic.Field()
    """
    Stripe invoice ID.
    """

    pdf_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to the PDF version of the invoice (currently not available).
    """

    status: str = pydantic.Field()
    """
    Invoice status (e.g. "paid", "open").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
