# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .feature_value import FeatureValue


class PricingPlan(UniversalBaseModel):
    """
    A single plan formatted for pricing page display.
    """

    display_name: str
    feature_values: typing.Dict[str, FeatureValue]
    key: str
    price: int
    price_display: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
