# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pricing_billing import PricingBilling
from .pricing_feature import PricingFeature
from .pricing_metadata import PricingMetadata
from .pricing_plan import PricingPlan
from .rate_card_response import RateCardResponse


class PricingResponse(UniversalBaseModel):
    """
    Top-level pricing response returned by `GET /pricing`.
    """

    billing: typing.Optional[PricingBilling] = None
    features: typing.List[PricingFeature]
    metadata: PricingMetadata
    plans: typing.List[PricingPlan]
    rate_card: typing.Optional[RateCardResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
