# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RateCardDimension(UniversalBaseModel):
    """
    A single dimension of the platform rate card.
    """

    code: str
    display_name: str
    free_tier: int
    free_tier_display: str
    unit_price_cents: int
    unit_price_display: str
    unit_size: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
