# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RegisterSubjectRequest(UniversalBaseModel):
    """
    Request body for `POST /subjects`.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address for the subject (required for invoicing).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name for the subject.
    """

    plan_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plan key to assign (defaults to tenant's default plan if unset).
    """

    subject_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
