# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .monthly_revenue import MonthlyRevenue


class RevenueResponse(UniversalBaseModel):
    """
    Response body for `GET /invoices/revenue`.
    """

    month_over_month: typing.List[MonthlyRevenue] = pydantic.Field()
    """
    Per-month breakdown, sorted chronologically (oldest first).
    """

    total_collected_cents: int = pydantic.Field()
    """
    Sum of `amount_cents` for all invoices with status "paid".
    """

    total_invoiced_cents: int = pydantic.Field()
    """
    Sum of `amount_cents` across all invoices.
    """

    total_outstanding_cents: int = pydantic.Field()
    """
    Sum of `amount_cents` for all invoices whose status is outstanding
    (money still owed): "open", "past_due", or "payment_failed".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
