# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .addon_definition import AddonDefinition
from .billing_config import BillingConfig
from .contract_definition import ContractDefinition
from .feature_definition import FeatureDefinition
from .plan_definition import PlanDefinition


class SchemaDocument(UniversalBaseModel):
    """
    Top-level schema document uploaded by tenants.
    """

    addons: typing.Optional[typing.Dict[str, typing.Optional[AddonDefinition]]] = None
    billing: typing.Optional[BillingConfig] = None
    custom_contracts: typing.Optional[typing.Dict[str, typing.Optional[ContractDefinition]]] = None
    default_plan: typing.Optional[str] = None
    features: typing.Dict[str, FeatureDefinition]
    plans: typing.Dict[str, PlanDefinition]
    version: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
