# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SetUsageRejection(UniversalBaseModel):
    """
    Rejection response for `PUT /subjects/{subject_id}/usage/{feature_code}` (409).
    """

    accepted: bool = pydantic.Field()
    """
    Always `false` for a rejected set.
    """

    current_value: typing.Optional[int] = pydantic.Field(default=None)
    """
    The current counter value (if available).
    """

    max: typing.Optional[int] = pydantic.Field(default=None)
    """
    The effective limit for this feature (if applicable).
    """

    reason: str = pydantic.Field()
    """
    Human-readable reason for the rejection.
    """

    requested_value: typing.Optional[int] = pydantic.Field(default=None)
    """
    The value that was requested (if applicable).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
