# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SetUsageResponse(UniversalBaseModel):
    """
    Successful response for `PUT /subjects/{subject_id}/usage/{feature_code}`.
    """

    accepted: bool = pydantic.Field()
    """
    Always `true` for a successful set.
    """

    max: typing.Optional[int] = pydantic.Field(default=None)
    """
    The effective limit for this feature, if applicable.
    """

    new_value: int = pydantic.Field()
    """
    The counter value after this write (equals the requested value).
    """

    previous_value: int = pydantic.Field()
    """
    The counter value before this write.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
