# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TenantMeResponse(UniversalBaseModel):
    """
    Response body for `GET /tenants/me`.
    """

    created_at: str
    org_id: str
    plan_key: str
    stripe_customer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stripe Customer ID on the platform account, if a payment method has been
    collected for this tenant. Absent (omitted) if none is on file.
    """

    tenant_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
