# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .feature_usage import FeatureUsage


class UsageResponse(UniversalBaseModel):
    """
    Response body for `GET /usage`.
    """

    billing_period_end: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    End of the current billing period (ISO 8601). Only present when billing is configured.
    """

    billing_period_start: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Start of the current billing period (ISO 8601). Only present when billing is configured.
    """

    features: typing.List[FeatureUsage]
    total_api_calls: int = pydantic.Field()
    """
    Total API calls across all metered features.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
