# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.invoice_preview_response import InvoicePreviewResponse
from ..types.list_invoice_failures_response import ListInvoiceFailuresResponse
from ..types.list_invoices_response import ListInvoicesResponse
from ..types.list_platform_invoices_response import ListPlatformInvoicesResponse
from ..types.revenue_response import RevenueResponse
from .raw_client import AsyncRawInvoicesClient, RawInvoicesClient


class InvoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvoicesClient
        """
        return self._raw_client

    def list_invoice_failures(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        exhausted: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoiceFailuresResponse:
        """
        Lists invoice-failure markers for the authenticated tenant, most recent
        failure first, with optional filtering by `subject_id` and `exhausted`.
        Supports cursor-based pagination.

        Query parameters:
        - `subject_id` — filter by subject
        - `exhausted` — `true`/`false` to filter by retry-budget status
        - `limit` — maximum number of items per page (1–1000, default 100)
        - `cursor` — opaque pagination cursor from a previous response

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        exhausted : typing.Optional[bool]
            Filter by retry-budget status (true = exhausted)

        limit : typing.Optional[int]
            Maximum items per page (1–1000, default 100)

        cursor : typing.Optional[str]
            Opaque pagination cursor from previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoiceFailuresResponse
            List of invoice-failure markers

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.list_invoice_failures()
        """
        _response = self._raw_client.list_invoice_failures(
            subject_id=subject_id, exhausted=exhausted, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoicesResponse:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range. Supports cursor-based pagination.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible).
          Any other value is rejected with a 400.
        - `start_date` — RFC 3339 datetime; only invoices overlapping this date or later.
          Must be a valid RFC 3339 timestamp, or the request is rejected with a 400.
        - `end_date` — RFC 3339 datetime; only invoices overlapping this date or earlier.
          Must be a valid RFC 3339 timestamp, or the request is rejected with a 400.
        - `limit` — maximum number of items per page (1–1000, default 100)
        - `cursor` — opaque pagination cursor from a previous response

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            RFC 3339 start date filter

        end_date : typing.Optional[str]
            RFC 3339 end date filter

        limit : typing.Optional[int]
            Maximum items per page (1–1000, default 100)

        cursor : typing.Optional[str]
            Opaque pagination cursor from previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoicesResponse
            List of invoices

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.list_invoices()
        """
        _response = self._raw_client.list_invoices(
            subject_id=subject_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def list_platform_invoices(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPlatformInvoicesResponse:
        """
        Lists Billkit's platform invoices for the authenticated tenant (charges from
        Billkit to the tenant). Returns all platform invoices sorted by `created_at`
        descending (most recent first).

        Platform invoices are bounded (~12-24 per year) so no pagination is needed.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPlatformInvoicesResponse
            List of platform invoices

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.list_platform_invoices()
        """
        _response = self._raw_client.list_platform_invoices(request_options=request_options)
        return _response.data

    def get_revenue(self, *, request_options: typing.Optional[RequestOptions] = None) -> RevenueResponse:
        """
        Aggregates revenue metrics from all end-user invoices for the authenticated
        tenant. Returns totals and a month-over-month breakdown grouped by
        `billing_period_end`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevenueResponse
            Revenue metrics

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.get_revenue()
        """
        _response = self._raw_client.get_revenue(request_options=request_options)
        return _response.data

    def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvoicePreviewResponse:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoicePreviewResponse
            Invoice preview

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.preview_invoice(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.preview_invoice(subject_id, request_options=request_options)
        return _response.data


class AsyncInvoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvoicesClient
        """
        return self._raw_client

    async def list_invoice_failures(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        exhausted: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoiceFailuresResponse:
        """
        Lists invoice-failure markers for the authenticated tenant, most recent
        failure first, with optional filtering by `subject_id` and `exhausted`.
        Supports cursor-based pagination.

        Query parameters:
        - `subject_id` — filter by subject
        - `exhausted` — `true`/`false` to filter by retry-budget status
        - `limit` — maximum number of items per page (1–1000, default 100)
        - `cursor` — opaque pagination cursor from a previous response

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        exhausted : typing.Optional[bool]
            Filter by retry-budget status (true = exhausted)

        limit : typing.Optional[int]
            Maximum items per page (1–1000, default 100)

        cursor : typing.Optional[str]
            Opaque pagination cursor from previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoiceFailuresResponse
            List of invoice-failure markers

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.list_invoice_failures()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invoice_failures(
            subject_id=subject_id, exhausted=exhausted, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoicesResponse:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range. Supports cursor-based pagination.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible).
          Any other value is rejected with a 400.
        - `start_date` — RFC 3339 datetime; only invoices overlapping this date or later.
          Must be a valid RFC 3339 timestamp, or the request is rejected with a 400.
        - `end_date` — RFC 3339 datetime; only invoices overlapping this date or earlier.
          Must be a valid RFC 3339 timestamp, or the request is rejected with a 400.
        - `limit` — maximum number of items per page (1–1000, default 100)
        - `cursor` — opaque pagination cursor from a previous response

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            RFC 3339 start date filter

        end_date : typing.Optional[str]
            RFC 3339 end date filter

        limit : typing.Optional[int]
            Maximum items per page (1–1000, default 100)

        cursor : typing.Optional[str]
            Opaque pagination cursor from previous response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoicesResponse
            List of invoices

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.list_invoices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invoices(
            subject_id=subject_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def list_platform_invoices(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPlatformInvoicesResponse:
        """
        Lists Billkit's platform invoices for the authenticated tenant (charges from
        Billkit to the tenant). Returns all platform invoices sorted by `created_at`
        descending (most recent first).

        Platform invoices are bounded (~12-24 per year) so no pagination is needed.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPlatformInvoicesResponse
            List of platform invoices

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.list_platform_invoices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_platform_invoices(request_options=request_options)
        return _response.data

    async def get_revenue(self, *, request_options: typing.Optional[RequestOptions] = None) -> RevenueResponse:
        """
        Aggregates revenue metrics from all end-user invoices for the authenticated
        tenant. Returns totals and a month-over-month breakdown grouped by
        `billing_period_end`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevenueResponse
            Revenue metrics

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.get_revenue()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_revenue(request_options=request_options)
        return _response.data

    async def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvoicePreviewResponse:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoicePreviewResponse
            Invoice preview

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.preview_invoice(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_invoice(subject_id, request_options=request_options)
        return _response.data
