# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.invoice_preview_response import InvoicePreviewResponse
from ..types.list_invoices_response import ListInvoicesResponse
from .raw_client import AsyncRawInvoicesClient, RawInvoicesClient


class InvoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvoicesClient
        """
        return self._raw_client

    def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoicesResponse:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible)
        - `start_date` — ISO 8601 datetime; only invoices overlapping this date or later
        - `end_date` — ISO 8601 datetime; only invoices overlapping this date or earlier

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            ISO 8601 start date filter

        end_date : typing.Optional[str]
            ISO 8601 end date filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoicesResponse
            List of invoices

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.list_invoices()
        """
        _response = self._raw_client.list_invoices(
            subject_id=subject_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            request_options=request_options,
        )
        return _response.data

    def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvoicePreviewResponse:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoicePreviewResponse
            Invoice preview

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.invoices.preview_invoice(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.preview_invoice(subject_id, request_options=request_options)
        return _response.data


class AsyncInvoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvoicesClient
        """
        return self._raw_client

    async def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInvoicesResponse:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible)
        - `start_date` — ISO 8601 datetime; only invoices overlapping this date or later
        - `end_date` — ISO 8601 datetime; only invoices overlapping this date or earlier

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            ISO 8601 start date filter

        end_date : typing.Optional[str]
            ISO 8601 end date filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInvoicesResponse
            List of invoices

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.list_invoices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invoices(
            subject_id=subject_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            request_options=request_options,
        )
        return _response.data

    async def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvoicePreviewResponse:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoicePreviewResponse
            Invoice preview

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.invoices.preview_invoice(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_invoice(subject_id, request_options=request_options)
        return _response.data
