# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.invoice_preview_response import InvoicePreviewResponse
from ..types.list_invoices_response import ListInvoicesResponse
from pydantic import ValidationError


class RawInvoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListInvoicesResponse]:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible)
        - `start_date` — ISO 8601 datetime; only invoices overlapping this date or later
        - `end_date` — ISO 8601 datetime; only invoices overlapping this date or earlier

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            ISO 8601 start date filter

        end_date : typing.Optional[str]
            ISO 8601 end date filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListInvoicesResponse]
            List of invoices
        """
        _response = self._client_wrapper.httpx_client.request(
            "invoices",
            method="GET",
            params={
                "subject_id": subject_id,
                "status": status,
                "start_date": start_date,
                "end_date": end_date,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListInvoicesResponse,
                    parse_obj_as(
                        type_=ListInvoicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[InvoicePreviewResponse]:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[InvoicePreviewResponse]
            Invoice preview
        """
        _response = self._client_wrapper.httpx_client.request(
            f"invoices/{encode_path_param(subject_id)}/preview",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InvoicePreviewResponse,
                    parse_obj_as(
                        type_=InvoicePreviewResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInvoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_invoices(
        self,
        *,
        subject_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListInvoicesResponse]:
        """
        Lists end-user invoices for the authenticated tenant with optional filtering
        by subject_id, status, and date range.

        Query parameters:
        - `subject_id` — filter by subject
        - `status` — filter by invoice status (open, paid, past_due, uncollectible)
        - `start_date` — ISO 8601 datetime; only invoices overlapping this date or later
        - `end_date` — ISO 8601 datetime; only invoices overlapping this date or earlier

        Parameters
        ----------
        subject_id : typing.Optional[str]
            Filter by subject ID

        status : typing.Optional[str]
            Filter by status (open, paid, past_due, uncollectible)

        start_date : typing.Optional[str]
            ISO 8601 start date filter

        end_date : typing.Optional[str]
            ISO 8601 end date filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListInvoicesResponse]
            List of invoices
        """
        _response = await self._client_wrapper.httpx_client.request(
            "invoices",
            method="GET",
            params={
                "subject_id": subject_id,
                "status": status,
                "start_date": start_date,
                "end_date": end_date,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListInvoicesResponse,
                    parse_obj_as(
                        type_=ListInvoicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def preview_invoice(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[InvoicePreviewResponse]:
        """
        Calculates what the next invoice would look like for a subject based on
        their current usage, plan assignment, and schema billing configuration.

        Returns:
        - 200 with the preview if billable usage exists
        - 404 if the subject is not found or has no plan assignment
        - 422 if no billing config or Connect account is configured

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[InvoicePreviewResponse]
            Invoice preview
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"invoices/{encode_path_param(subject_id)}/preview",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InvoicePreviewResponse,
                    parse_obj_as(
                        type_=InvoicePreviewResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
