# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.validation_error_response import ValidationErrorResponse
from .raw_client import AsyncRawSchemaClient, RawSchemaClient


class SchemaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSchemaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSchemaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSchemaClient
        """
        return self._raw_client

    def get_schema(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        Retrieves the tenant's own schema document from the store.
        Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If the tenant has a schema: returns 200 with the schema document body (as stored).
        - If the tenant has no schema: returns 404 with `{ "error": "schema not found" }`.
        - If a store error occurs: returns 500 with `{ "error": "internal error" }`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Schema document (YAML or JSON)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.schema.get_schema()
        """
        _response = self._raw_client.get_schema(request_options=request_options)
        return _response.data

    def put_schema(self, *, request_options: typing.Optional[RequestOptions] = None) -> ValidationErrorResponse:
        """
        Validates, persists to store, and invalidates all tenant cache entries.
        Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If the body is empty: returns 400.
        - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }` (not persisted).
        - If the document is valid: persists to store, invalidates cache, returns 200 with `{ "valid": true, "errors": [] }`.
        - If a store or cache error occurs: returns 500.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationErrorResponse
            Validation result (persisted if valid)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.schema.put_schema()
        """
        _response = self._raw_client.put_schema(request_options=request_options)
        return _response.data

    def validate_schema(self, *, request_options: typing.Optional[RequestOptions] = None) -> ValidationErrorResponse:
        """
        Accepts a raw schema document body (YAML or JSON), runs the full validator
        (structural + semantic), and returns a `ValidationErrorResponse` without
        persisting anything.

        - If the document is valid: returns 200 with `{ "valid": true, "errors": [] }`.
        - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }`.
        - If the body is empty: returns 400.

        This endpoint is protected by the auth middleware (X-Api-Key), but does not
        use the tenant context since validation is stateless.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationErrorResponse
            Validation result

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.schema.validate_schema()
        """
        _response = self._raw_client.validate_schema(request_options=request_options)
        return _response.data


class AsyncSchemaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSchemaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSchemaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSchemaClient
        """
        return self._raw_client

    async def get_schema(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        Retrieves the tenant's own schema document from the store.
        Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If the tenant has a schema: returns 200 with the schema document body (as stored).
        - If the tenant has no schema: returns 404 with `{ "error": "schema not found" }`.
        - If a store error occurs: returns 500 with `{ "error": "internal error" }`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Schema document (YAML or JSON)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.schema.get_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schema(request_options=request_options)
        return _response.data

    async def put_schema(self, *, request_options: typing.Optional[RequestOptions] = None) -> ValidationErrorResponse:
        """
        Validates, persists to store, and invalidates all tenant cache entries.
        Tenant is resolved from `X-Api-Key` via the auth middleware.

        - If the body is empty: returns 400.
        - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }` (not persisted).
        - If the document is valid: persists to store, invalidates cache, returns 200 with `{ "valid": true, "errors": [] }`.
        - If a store or cache error occurs: returns 500.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationErrorResponse
            Validation result (persisted if valid)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.schema.put_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.put_schema(request_options=request_options)
        return _response.data

    async def validate_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ValidationErrorResponse:
        """
        Accepts a raw schema document body (YAML or JSON), runs the full validator
        (structural + semantic), and returns a `ValidationErrorResponse` without
        persisting anything.

        - If the document is valid: returns 200 with `{ "valid": true, "errors": [] }`.
        - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }`.
        - If the body is empty: returns 400.

        This endpoint is protected by the auth middleware (X-Api-Key), but does not
        use the tenant context since validation is stateless.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationErrorResponse
            Validation result

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.schema.validate_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_schema(request_options=request_options)
        return _response.data
