# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.batch_register_response import BatchRegisterResponse
from ..types.register_subject_request import RegisterSubjectRequest
from ..types.register_subject_response import RegisterSubjectResponse
from ..types.subject_detail_response import SubjectDetailResponse
from ..types.subjects_response import SubjectsResponse
from .raw_client import AsyncRawSubjectsClient, RawSubjectsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubjectsClient
        """
        return self._raw_client

    def list_subjects(self, *, request_options: typing.Optional[RequestOptions] = None) -> SubjectsResponse:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectsResponse
            List of subjects

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.list_subjects()
        """
        _response = self._raw_client.list_subjects(request_options=request_options)
        return _response.data

    def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterSubjectResponse:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterSubjectResponse
            Subject re-registered (updated)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.register_subject(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.register_subject(
            subject_id=subject_id, email=email, name=name, plan_key=plan_key, request_options=request_options
        )
        return _response.data

    def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchRegisterResponse:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchRegisterResponse
            Batch registration results

        Examples
        --------
        from billkit import BillkitApi, RegisterSubjectRequest

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.register_subjects_batch(
            subjects=[
                RegisterSubjectRequest(
                    subject_id="subject_id",
                )
            ],
        )
        """
        _response = self._raw_client.register_subjects_batch(subjects=subjects, request_options=request_options)
        return _response.data

    def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubjectDetailResponse:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectDetailResponse
            Subject details

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.get_subject(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.get_subject(subject_id, request_options=request_options)
        return _response.data


class AsyncSubjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubjectsClient
        """
        return self._raw_client

    async def list_subjects(self, *, request_options: typing.Optional[RequestOptions] = None) -> SubjectsResponse:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectsResponse
            List of subjects

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.list_subjects()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_subjects(request_options=request_options)
        return _response.data

    async def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterSubjectResponse:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterSubjectResponse
            Subject re-registered (updated)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.register_subject(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_subject(
            subject_id=subject_id, email=email, name=name, plan_key=plan_key, request_options=request_options
        )
        return _response.data

    async def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchRegisterResponse:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchRegisterResponse
            Batch registration results

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi, RegisterSubjectRequest

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.register_subjects_batch(
                subjects=[
                    RegisterSubjectRequest(
                        subject_id="subject_id",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_subjects_batch(subjects=subjects, request_options=request_options)
        return _response.data

    async def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubjectDetailResponse:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectDetailResponse
            Subject details

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.get_subject(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subject(subject_id, request_options=request_options)
        return _response.data
