# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.batch_register_response import BatchRegisterResponse
from ..types.checkout_fallback_response import CheckoutFallbackResponse
from ..types.checkout_session_response import CheckoutSessionResponse
from ..types.register_subject_request import RegisterSubjectRequest
from ..types.register_subject_response import RegisterSubjectResponse
from ..types.subject_detail_response import SubjectDetailResponse
from ..types.subjects_response import SubjectsResponse
from .raw_client import AsyncRawSubjectsClient, RawSubjectsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubjectsClient
        """
        return self._raw_client

    def list_subjects(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubjectsResponse:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return per page.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `next_cursor` field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectsResponse
            List of subjects

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.list_subjects()
        """
        _response = self._raw_client.list_subjects(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterSubjectResponse:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        `plan_key` is validated against the tenant's schema, mirroring `POST /assignments`:
        - If `plan_key` is provided but does not exist in the schema: returns 422.
        - If `plan_key` is omitted, it defaults to the schema's `default_plan` (not the
          literal string `"free"`). If the schema defines no `default_plan`: returns 422.
        - If the tenant has no schema uploaded at all: returns 422.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/plan_key/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterSubjectResponse
            Subject re-registered (updated)

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.register_subject(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.register_subject(
            subject_id=subject_id, email=email, name=name, plan_key=plan_key, request_options=request_options
        )
        return _response.data

    def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchRegisterResponse:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchRegisterResponse
            Batch registration results

        Examples
        --------
        from billkit import BillkitApi, RegisterSubjectRequest

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.register_subjects_batch(
            subjects=[
                RegisterSubjectRequest(
                    subject_id="subject_id",
                )
            ],
        )
        """
        _response = self._raw_client.register_subjects_batch(subjects=subjects, request_options=request_options)
        return _response.data

    def create_checkout_fallback(
        self,
        *,
        email: str,
        payment_method_id: str,
        subject_id: str,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutFallbackResponse:
        """
        **Non-default.** Requires the tenant to build their own card-entry UI, which
        violates the zero-tenant-code principle (NFR-4) — the hosted
        `POST /subjects/checkout-session` is the recommended path. This exists only
        for tenants who deliberately want their payment UI on their own domain.

        Behavior (converges on the same outcome as the hosted path):
        1. Create/reference the subject; ensure a Stripe Customer.
        2. Set the supplied `payment_method_id` as the customer's default so
           recurring charges auto-charge off-session (US-10).
        3. **Prepaid:** charge the first window base off-session (reusing the
           `create_and_finalize_proration_invoice` path) and idempotently claim the
           window-1 `Base` `InvoiceRecord` (same deterministic id as the hosted path
           and the recurring `invoice_job`). **Postpaid:** no charge at signup.
        4. Elevate the subject to `billable`.

        Parameters
        ----------
        email : str

        payment_method_id : str
            The confirmed payment method id captured by the tenant's own card form.

        subject_id : str

        name : typing.Optional[str]

        plan_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutFallbackResponse
            Subject onboarded via embedded fallback

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.create_checkout_fallback(
            email="email",
            payment_method_id="payment_method_id",
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.create_checkout_fallback(
            email=email,
            payment_method_id=payment_method_id,
            subject_id=subject_id,
            name=name,
            plan_key=plan_key,
            request_options=request_options,
        )
        return _response.data

    def create_checkout_session(
        self,
        *,
        cancel_url: str,
        email: str,
        subject_id: str,
        success_url: str,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutSessionResponse:
        """
        Creates (or references) a subject in the `pending_checkout` state and returns
        a Stripe-hosted onboarding URL, with the Session mode branched from the
        schema's `billing_mode` (prepaid ⇒ `payment`, postpaid ⇒ `setup`). The
        tenant-facing contract is identical for both modes.

        - 400 if `subject_id`/`email`/`success_url`/`cancel_url` are missing.
        - 422 if no schema is uploaded, or `plan_key` is not in the schema, or (for
          prepaid) the resolved plan has no positive `price` to charge.
        - 409 if the subject already exists and is already billable (paid) — nothing
          to onboard.
        - 502 if Stripe fails (Customer or Session creation). The subject is left in
          a retryable state.
        - 200 with `{ url, session_id, billing_mode }` on success.

        Parameters
        ----------
        cancel_url : str
            Where Stripe redirects the subject on cancel.

        email : str
            Email for the Stripe Customer / receipts (required to create a Customer).

        subject_id : str
            The subject to onboard. Created (in `pending_checkout` state) if new;
            referenced if it already exists.

        success_url : str
            Where Stripe redirects the subject on success.

        name : typing.Optional[str]
            Optional display name.

        plan_key : typing.Optional[str]
            Plan to onboard onto. Defaults to the schema's `default_plan` when unset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSessionResponse
            Hosted onboarding session created

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.create_checkout_session(
            cancel_url="cancel_url",
            email="email",
            subject_id="subject_id",
            success_url="success_url",
        )
        """
        _response = self._raw_client.create_checkout_session(
            cancel_url=cancel_url,
            email=email,
            subject_id=subject_id,
            success_url=success_url,
            name=name,
            plan_key=plan_key,
            request_options=request_options,
        )
        return _response.data

    def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubjectDetailResponse:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectDetailResponse
            Subject details

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.subjects.get_subject(
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.get_subject(subject_id, request_options=request_options)
        return _response.data


class AsyncSubjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubjectsClient
        """
        return self._raw_client

    async def list_subjects(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SubjectsResponse:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return per page.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `next_cursor` field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectsResponse
            List of subjects

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.list_subjects()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_subjects(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RegisterSubjectResponse:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        `plan_key` is validated against the tenant's schema, mirroring `POST /assignments`:
        - If `plan_key` is provided but does not exist in the schema: returns 422.
        - If `plan_key` is omitted, it defaults to the schema's `default_plan` (not the
          literal string `"free"`). If the schema defines no `default_plan`: returns 422.
        - If the tenant has no schema uploaded at all: returns 422.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/plan_key/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RegisterSubjectResponse
            Subject re-registered (updated)

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.register_subject(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_subject(
            subject_id=subject_id, email=email, name=name, plan_key=plan_key, request_options=request_options
        )
        return _response.data

    async def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchRegisterResponse:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchRegisterResponse
            Batch registration results

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi, RegisterSubjectRequest

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.register_subjects_batch(
                subjects=[
                    RegisterSubjectRequest(
                        subject_id="subject_id",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_subjects_batch(subjects=subjects, request_options=request_options)
        return _response.data

    async def create_checkout_fallback(
        self,
        *,
        email: str,
        payment_method_id: str,
        subject_id: str,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutFallbackResponse:
        """
        **Non-default.** Requires the tenant to build their own card-entry UI, which
        violates the zero-tenant-code principle (NFR-4) — the hosted
        `POST /subjects/checkout-session` is the recommended path. This exists only
        for tenants who deliberately want their payment UI on their own domain.

        Behavior (converges on the same outcome as the hosted path):
        1. Create/reference the subject; ensure a Stripe Customer.
        2. Set the supplied `payment_method_id` as the customer's default so
           recurring charges auto-charge off-session (US-10).
        3. **Prepaid:** charge the first window base off-session (reusing the
           `create_and_finalize_proration_invoice` path) and idempotently claim the
           window-1 `Base` `InvoiceRecord` (same deterministic id as the hosted path
           and the recurring `invoice_job`). **Postpaid:** no charge at signup.
        4. Elevate the subject to `billable`.

        Parameters
        ----------
        email : str

        payment_method_id : str
            The confirmed payment method id captured by the tenant's own card form.

        subject_id : str

        name : typing.Optional[str]

        plan_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutFallbackResponse
            Subject onboarded via embedded fallback

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.create_checkout_fallback(
                email="email",
                payment_method_id="payment_method_id",
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_checkout_fallback(
            email=email,
            payment_method_id=payment_method_id,
            subject_id=subject_id,
            name=name,
            plan_key=plan_key,
            request_options=request_options,
        )
        return _response.data

    async def create_checkout_session(
        self,
        *,
        cancel_url: str,
        email: str,
        subject_id: str,
        success_url: str,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutSessionResponse:
        """
        Creates (or references) a subject in the `pending_checkout` state and returns
        a Stripe-hosted onboarding URL, with the Session mode branched from the
        schema's `billing_mode` (prepaid ⇒ `payment`, postpaid ⇒ `setup`). The
        tenant-facing contract is identical for both modes.

        - 400 if `subject_id`/`email`/`success_url`/`cancel_url` are missing.
        - 422 if no schema is uploaded, or `plan_key` is not in the schema, or (for
          prepaid) the resolved plan has no positive `price` to charge.
        - 409 if the subject already exists and is already billable (paid) — nothing
          to onboard.
        - 502 if Stripe fails (Customer or Session creation). The subject is left in
          a retryable state.
        - 200 with `{ url, session_id, billing_mode }` on success.

        Parameters
        ----------
        cancel_url : str
            Where Stripe redirects the subject on cancel.

        email : str
            Email for the Stripe Customer / receipts (required to create a Customer).

        subject_id : str
            The subject to onboard. Created (in `pending_checkout` state) if new;
            referenced if it already exists.

        success_url : str
            Where Stripe redirects the subject on success.

        name : typing.Optional[str]
            Optional display name.

        plan_key : typing.Optional[str]
            Plan to onboard onto. Defaults to the schema's `default_plan` when unset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSessionResponse
            Hosted onboarding session created

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.create_checkout_session(
                cancel_url="cancel_url",
                email="email",
                subject_id="subject_id",
                success_url="success_url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_checkout_session(
            cancel_url=cancel_url,
            email=email,
            subject_id=subject_id,
            success_url=success_url,
            name=name,
            plan_key=plan_key,
            request_options=request_options,
        )
        return _response.data

    async def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubjectDetailResponse:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubjectDetailResponse
            Subject details

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.subjects.get_subject(
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subject(subject_id, request_options=request_options)
        return _response.data
