# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.batch_register_response import BatchRegisterResponse
from ..types.register_subject_request import RegisterSubjectRequest
from ..types.register_subject_response import RegisterSubjectResponse
from ..types.subject_detail_response import SubjectDetailResponse
from ..types.subjects_response import SubjectsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSubjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_subjects(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SubjectsResponse]:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return per page.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `next_cursor` field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubjectsResponse]
            List of subjects
        """
        _response = self._client_wrapper.httpx_client.request(
            "subjects",
            method="GET",
            params={
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubjectsResponse,
                    parse_obj_as(
                        type_=SubjectsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RegisterSubjectResponse]:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        `plan_key` is validated against the tenant's schema, mirroring `POST /assignments`:
        - If `plan_key` is provided but does not exist in the schema: returns 422.
        - If `plan_key` is omitted, it defaults to the schema's `default_plan` (not the
          literal string `"free"`). If the schema defines no `default_plan`: returns 422.
        - If the tenant has no schema uploaded at all: returns 422.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/plan_key/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RegisterSubjectResponse]
            Subject re-registered (updated)
        """
        _response = self._client_wrapper.httpx_client.request(
            "subjects",
            method="POST",
            json={
                "email": email,
                "name": name,
                "plan_key": plan_key,
                "subject_id": subject_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RegisterSubjectResponse,
                    parse_obj_as(
                        type_=RegisterSubjectResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BatchRegisterResponse]:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BatchRegisterResponse]
            Batch registration results
        """
        _response = self._client_wrapper.httpx_client.request(
            "subjects/batch",
            method="POST",
            json={
                "subjects": convert_and_respect_annotation_metadata(
                    object_=subjects, annotation=typing.Sequence[RegisterSubjectRequest], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchRegisterResponse,
                    parse_obj_as(
                        type_=BatchRegisterResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SubjectDetailResponse]:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubjectDetailResponse]
            Subject details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"subjects/{encode_path_param(subject_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubjectDetailResponse,
                    parse_obj_as(
                        type_=SubjectDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSubjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_subjects(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SubjectsResponse]:
        """
        Returns all subject assignments for the authenticated tenant.
        The tenant is resolved from `X-Api-Key` via the auth middleware.

        - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
        - If authenticated with the system API key: returns all subjects under the system tenant.
        - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
        - If a DynamoDB failure occurs: returns HTTP 500.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return per page.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `next_cursor` field.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubjectsResponse]
            List of subjects
        """
        _response = await self._client_wrapper.httpx_client.request(
            "subjects",
            method="GET",
            params={
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubjectsResponse,
                    parse_obj_as(
                        type_=SubjectsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def register_subject(
        self,
        *,
        subject_id: str,
        email: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        plan_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RegisterSubjectResponse]:
        """
        Registers a subject with optional email and name. If an email is provided
        and the tenant has an active Stripe Connect account, creates a Stripe Customer
        on the connected account and marks the subject as "billable".

        If the subject already exists (re-registration), updates the Stripe Customer's
        email/name rather than creating a duplicate.

        `plan_key` is validated against the tenant's schema, mirroring `POST /assignments`:
        - If `plan_key` is provided but does not exist in the schema: returns 422.
        - If `plan_key` is omitted, it defaults to the schema's `default_plan` (not the
          literal string `"free"`). If the schema defines no `default_plan`: returns 422.
        - If the tenant has no schema uploaded at all: returns 422.

        - If subject_id is missing or too long: returns 400.
        - If the subject already exists: updates email/name/plan_key/Stripe Customer (idempotent).
        - If no Stripe Connect account is active: subject is stored without Stripe Customer.
        - If Stripe API fails: returns 502 (subject is NOT partially created).
        - On success: returns 201 (new) or 200 (re-registration).

        Parameters
        ----------
        subject_id : str

        email : typing.Optional[str]
            Email address for the subject (required for invoicing).

        name : typing.Optional[str]
            Display name for the subject.

        plan_key : typing.Optional[str]
            Plan key to assign (defaults to tenant's default plan if unset).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RegisterSubjectResponse]
            Subject re-registered (updated)
        """
        _response = await self._client_wrapper.httpx_client.request(
            "subjects",
            method="POST",
            json={
                "email": email,
                "name": name,
                "plan_key": plan_key,
                "subject_id": subject_id,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RegisterSubjectResponse,
                    parse_obj_as(
                        type_=RegisterSubjectResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def register_subjects_batch(
        self,
        *,
        subjects: typing.Sequence[RegisterSubjectRequest],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BatchRegisterResponse]:
        """
        Registers multiple subjects in a single request. Creates Stripe Customers
        for each subject that has an email and where the tenant has active Connect.

        - If the batch exceeds 100 subjects: returns 400.
        - Individual failures are reported per-subject (no rollback).
        - On success: returns 200 with results array.

        Parameters
        ----------
        subjects : typing.Sequence[RegisterSubjectRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BatchRegisterResponse]
            Batch registration results
        """
        _response = await self._client_wrapper.httpx_client.request(
            "subjects/batch",
            method="POST",
            json={
                "subjects": convert_and_respect_annotation_metadata(
                    object_=subjects, annotation=typing.Sequence[RegisterSubjectRequest], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BatchRegisterResponse,
                    parse_obj_as(
                        type_=BatchRegisterResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_subject(
        self, subject_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SubjectDetailResponse]:
        """
        Returns a single subject's details including plan, billing status,
        payment method status, and Stripe Customer ID.

        - If the subject does not exist: returns 404.
        - On success: returns 200 with full subject details.

        Parameters
        ----------
        subject_id : str
            The subject identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubjectDetailResponse]
            Subject details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"subjects/{encode_path_param(subject_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubjectDetailResponse,
                    parse_obj_as(
                        type_=SubjectDetailResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
