# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.apply_contract_response import ApplyContractResponse
from .raw_client import AsyncRawContractsClient, RawContractsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ContractsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawContractsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawContractsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawContractsClient
        """
        return self._raw_client

    def apply_contract(
        self, *, contract_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApplyContractResponse:
        """
        Validates that the contract key exists in the tenant's schema, applies it to
        the subject's existing assignment in the store, and invalidates the subject's
        cache entries.

        - If the request body is missing or malformed: returns 400 (via Axum rejection).
        - If subject_id or contract_key is empty: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the contract key does not exist in the schema: returns 422.
        - If the subject has no existing assignment: returns 404.
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the applied contract details.

        Parameters
        ----------
        contract_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplyContractResponse
            Contract applied

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.contracts.apply_contract(
            contract_key="contract_key",
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.apply_contract(
            contract_key=contract_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data


class AsyncContractsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawContractsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawContractsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawContractsClient
        """
        return self._raw_client

    async def apply_contract(
        self, *, contract_key: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApplyContractResponse:
        """
        Validates that the contract key exists in the tenant's schema, applies it to
        the subject's existing assignment in the store, and invalidates the subject's
        cache entries.

        - If the request body is missing or malformed: returns 400 (via Axum rejection).
        - If subject_id or contract_key is empty: returns 400.
        - If the tenant has no schema uploaded: returns 422.
        - If the contract key does not exist in the schema: returns 422.
        - If the subject has no existing assignment: returns 404.
        - If a store or cache error occurs: returns 500.
        - On success: returns 200 with the applied contract details.

        Parameters
        ----------
        contract_key : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplyContractResponse
            Contract applied

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.contracts.apply_contract(
                contract_key="contract_key",
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.apply_contract(
            contract_key=contract_key, subject_id=subject_id, request_options=request_options
        )
        return _response.data
