# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tenant_me_response import TenantMeResponse
from .raw_client import AsyncRawTenantsClient, RawTenantsClient


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    def get_tenant_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> TenantMeResponse:
        """
        Protected by the auth middleware. Returns metadata about the authenticated
        user's tenant. The tenant_id is resolved by the auth middleware, either from:
        1. The JWT `custom:tenant_id` claim (if present), or
        2. The `USER#{sub}` → `tenant_id` mapping in DynamoDB (the common path).

        This endpoint then verifies the tenant record itself exists in DynamoDB and
        returns its metadata.

        - 200: tenant record found — returns tenant metadata (tenant_id, org_id, plan_key, created_at).
        - 404: tenant_id was resolved from the user link but the TenantRecord is missing.
          This can happen after a partial database reset or data corruption.
        - 401: (from auth middleware) user has no tenant association — either no
          `custom:tenant_id` claim and no USER#{sub} link in DynamoDB. This is the
          normal state for users who haven't provisioned yet, or after a full DB reset.
        - 500: unexpected store error.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMeResponse
            Tenant metadata

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tenants.get_tenant_me()
        """
        _response = self._raw_client.get_tenant_me(request_options=request_options)
        return _response.data


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    async def get_tenant_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> TenantMeResponse:
        """
        Protected by the auth middleware. Returns metadata about the authenticated
        user's tenant. The tenant_id is resolved by the auth middleware, either from:
        1. The JWT `custom:tenant_id` claim (if present), or
        2. The `USER#{sub}` → `tenant_id` mapping in DynamoDB (the common path).

        This endpoint then verifies the tenant record itself exists in DynamoDB and
        returns its metadata.

        - 200: tenant record found — returns tenant metadata (tenant_id, org_id, plan_key, created_at).
        - 404: tenant_id was resolved from the user link but the TenantRecord is missing.
          This can happen after a partial database reset or data corruption.
        - 401: (from auth middleware) user has no tenant association — either no
          `custom:tenant_id` claim and no USER#{sub} link in DynamoDB. This is the
          normal state for users who haven't provisioned yet, or after a full DB reset.
        - 500: unexpected store error.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMeResponse
            Tenant metadata

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tenants.get_tenant_me()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_tenant_me(request_options=request_options)
        return _response.data
