# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.gate_response import GateResponse
from .raw_client import AsyncRawEntitlementsClient, RawEntitlementsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EntitlementsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEntitlementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEntitlementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEntitlementsClient
        """
        return self._raw_client

    def check(
        self, *, feature_code: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GateResponse:
        """
        Authenticates via the auth middleware (X-Api-Key), resolves the entitlement
        configuration from cache/store, invokes the gate decision evaluator, increments
        the usage counter in cache for metered features, and returns a `GateResponse`.

        - If subject_id or feature_code is empty: returns 400.
        - If feature_code not found in schema: returns 404.
        - If subject has no plan assigned: returns 200 with `decision: "no_plan"`.
        - If a store error occurs: returns 500.
        - On success: returns 200 with the gate decision.

        Parameters
        ----------
        feature_code : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GateResponse
            Gate decision

        Examples
        --------
        from billkit import BillkitApi

        client = BillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.entitlements.check(
            feature_code="feature_code",
            subject_id="subject_id",
        )
        """
        _response = self._raw_client.check(
            feature_code=feature_code, subject_id=subject_id, request_options=request_options
        )
        return _response.data


class AsyncEntitlementsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEntitlementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEntitlementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEntitlementsClient
        """
        return self._raw_client

    async def check(
        self, *, feature_code: str, subject_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GateResponse:
        """
        Authenticates via the auth middleware (X-Api-Key), resolves the entitlement
        configuration from cache/store, invokes the gate decision evaluator, increments
        the usage counter in cache for metered features, and returns a `GateResponse`.

        - If subject_id or feature_code is empty: returns 400.
        - If feature_code not found in schema: returns 404.
        - If subject has no plan assigned: returns 200 with `decision: "no_plan"`.
        - If a store error occurs: returns 500.
        - On success: returns 200 with the gate decision.

        Parameters
        ----------
        feature_code : str

        subject_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GateResponse
            Gate decision

        Examples
        --------
        import asyncio

        from billkit import AsyncBillkitApi

        client = AsyncBillkitApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.entitlements.check(
                feature_code="feature_code",
                subject_id="subject_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.check(
            feature_code=feature_code, subject_id=subject_id, request_options=request_options
        )
        return _response.data
